src/gms/urls.py
from django.urls import path, include

from . import admin

urlpatterns = [
    path('', include('memberdb.urls')),
    path('admin/', admin.site.urls),
    path('payment/', include('squarepay.urls')),
]

src/memberdb/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from .views import MemberHomeView, MemberTokenView, EmailConfirmView
from .register import RegisterView, RenewView

app_name = 'memberdb'
urlpatterns = [
    path('', MemberHomeView.as_view(), name='home'),
    path('', MemberHomeView.as_view(), name='index'),

    # use the django-provided login views with our custom templates
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    # override the admin login/logout views
    path('admin/login/', auth_views.LoginView.as_view(template_name='login.html')),
    path('admin/logout/', auth_views.LogoutView.as_view(template_name='logout.html')),

    # for members to "login" before having created a user account
    path('login/<id>/<member_token>/', MemberTokenView.as_view(), name='login_member'),

    # email confirmation
    path('confirm/<int:pk>/<str:token>/', EmailConfirmView.as_view(), name='email_confirm'),
    
    path('register/', RegisterView.as_view(), name='register'),
    path('renew/', RenewView.as_view(), name='renew'),
    path('thanks/', TemplateView.as_view(template_name='thanks.html'), name='thanks'),
]

src/squarepay/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.utils import timezone

from memberdb.models import Membership, make_token

class CardPayment(models.Model):
    description     = models.CharField('Description', max_length=255)
    amount          = models.IntegerField('Amount in cents', null=False, blank=False)
    idempotency_key = models.CharField('Square Transactions API idempotency key', max_length=64, default=uuid.uuid1)
    is_paid         = models.BooleanField('Has been paid', blank=True, default=False)
    dispense_synced = models.BooleanField('Payment logged in dispense', blank=True, default=False)
    date_created    = models.DateTimeField('Date created', auto_now_add=True)
    date_paid       = models.DateTimeField('Date paid (payment captured)', null=True, blank=True)

    def set_paid(self):
        self.is_paid = True
        self.date_paid = timezone.now()
        self.save()

class MembershipPayment(CardPayment):
    """
    Link the payment to a specific membership
    """
    membership      = models.ForeignKey(Membership, on_delete=models.CASCADE, related_name='payments')

    def set_paid(self):
        self.membership.date_paid = timezone.now()
        self.membership.payment_method = 'online'
        super().set_paid()

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!-- MemberDB base template -->
	<title>{% block title %}UCC MemberDB{% endblock %}</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'ucc-logo.png' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static "memberdb.css" %}">
	{% block prestyle %}{% endblock %}
	<link rel="stylesheet" type="text/css" href="{% static "shared.css" %}">
	{% block extrahead %}{% endblock %}
	{% block extrastyle %}{% endblock %}
	{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
</head>

<body {% block bodyattrs %}{% endblock %}>


<!-- Container -->
<div id="container">
	{% block header_div %}<!-- Header -->
	<div id="header">
		{% block navbar %}
		<nav>
			{% block branding %}
			<a class="logo" title="UCCPortal homepage">
				<span></span>
			</a>
			{% endblock %}

			{# fancy automatic navbar thing from https://stackoverflow.com/questions/39639264 #}
			{% with url_name=request.resolver_match.url_name %}
			{% if request.member %}
			<a class="navtab {% if url_name == 'home' %}active{% endif %}" href="{% url "memberdb:home" %}">Member home</a>
			{% endif %}
			<a class="navtab {% if url_name == 'register' %}active{% endif %}" href="{% url "memberdb:register" %}">Register</a>

			{% if not request.user.is_authenticated %}
			<a class="navtab {% if url_name == 'login' %}active{% endif %}" href="{% url "memberdb:login" %}">Login</a>
			{% else %}
			<a class="navtab {% if url_name == 'renew' %}active{% endif %}" href="{% url "memberdb:renew" %}">Renew membership</a>

			{% if request.user.is_staff %}
			<a class="navtab {% block adminactive %}{% endblock %}" href="{% url "admin:index" %}">Admin site</a>
			{% endif %}

			{% endif %}

			{% if request.user.is_authenticated or request.member %}
			<a class="navtab {% if url_name == 'logout' %}active{% endif %}" href="{% url "memberdb:logout" %}">Logout</a>
			{% endif %}
			{% endwith %}

			{# add the groups class only if we have groups to display #}
			<div class="userinfo{% if request.user.is_authenticated %}{% if request.member %} groups{% endif %}">
				<span class="username">Welcome, {{ request.user.username }}</span>
				{% if request.member %}
				{% for g in request.member.groups %}<span class="group {{ g }}">{{ g }}</span>{% endfor %}
				{% endif %}
			{% else %}">
				<span class="username">Not logged in</span>
			{% endif %}
			</div>
		</nav>
		{% endblock %}

		{% block header %}{% endblock %}

	</div>
	{% endblock %}<!-- END Header -->
	{% block breadcrumbs %}{% endblock %}
	{% block messages %}{% if messages %}
	<ul class="messagelist">{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
	{% endfor %}</ul>
	{% endif %}{% endblock messages %}

	<!-- Content -->
	<div id="content">
		{% block pretitle %}{% endblock %}
		{% block content_title %}<h1></h1>{% endblock %}
		{% block content %}
		{% endblock %}
		<!-- sidebar -->
		{% block sidebar %}{% endblock %}
		<br class="clear">
	</div>
	<!-- END Content -->

	<!-- Footer -->
	{% block footer %}
	<div id="footer">
		<p>
			The University Computer Club Inc.
			ABN: 98 843 368 069
		</p>
		<div class="linkslist">
			<a href="https://www.ucc.asn.au">main website</a>&#8226;
			<a href="https://wiki.ucc.asn.au">UCC wiki</a>&#8226;
			<a href="https://www.ucc.asn.au/aboutucc/contact.ucc">contact us</a>&#8226;
			<a href="https://gitlab.ucc.asn.au/frekk/uccportal">source code</a>
		</div>
	</div>
	{% endblock %}
	<!-- END Footer -->
{% if DEPLOYMENT_ENV != "PROD" %}
<div class="watermark">{{DEPLOYMENT_ENV}}</div>
<style>
  .watermark {
	position: fixed;
	transform: translate(-50%, -50%);
	opacity: 0.3;
	{% if DEPLOYMENT_ENV == "STAGE" %}
	color: RED; 
	{% else %}
	color: GREEN; 
	{% endif %}
	font-size: 15em;
	top: 50%;
	left: 50%;
	pointer-events: none;
  }
</style>
{%endif %}
</div>
<!-- END Container -->

</body>
</html>

src/templates/base_form.html
{% extends "base.html" %}

{% block content_title %}<h1>Enter your details</h1>{% endblock %}

{% block content %}
<div class="form-container">
    <div class="form-header">
    <span class="tips">
    {% block tips %}
        Enter your details into the fields below, then click the button to save.
    {% endblock %}
    </span>
    </div>
    {% block form %}
    <form action="{% block action_url %}{% url 'memberdb:register' %}{% endblock %}" method="post">

        {% csrf_token %}

        {% if form.non_field_errors|length > 0 %}
            <p class="errornote">
                Please correct the errors below.
            </p>
            {{ form.non_field_errors }}
        {% endif %}

        {% block extra_preform %}{% endblock %}

        {% for field in form %}
        <div class="form-row">
            {{ field.errors }}
            {{ field.label_tag }}
            {{ field }}
            {% if field.field.help_text %}
            <p class="help">
            {{ field.field.help_text|safe }}
            </p>
            {% endif %}
        </div>
        {% endfor %}
        {% block postform %}{% endblock %}
        <div class="submit-row">
            <input type="submit" class="default" value="{% block action_text %}Register{% endblock %}">
        </div>
    </form>
    {% endblock %}
</div>
{% endblock %}

src/templates/home.html
{% extends "base_form.html" %}
{% load static %}
{% block title %}UCC Member Home{% endblock %}
{% block content_title %}
    <h1>Member home</h1>
    {% if request.member %}
    <h3>Welcome, {{ request.member.first_name }} {{ request.member.last_name }} (<code>{{ request.member.username }}</code>)</h3>
    {% else %}
    <h3>Welcome, {{ request.user.first_name }} {{ request.user.last_name }} (<code>{{ request.user.username }}</code>)</h3>
    {% endif %}
{% endblock %}

{% block tips %}
{% if not request.member %}
    {% if request.user.is_authenticated %}
    <b>You have no member record associated with this account.</b><br>
    Please <a href="{% url 'memberdb:renew' %}">renew your membership</a> to get started.
    <br><br>
    Note: you may have already paid for this year, but unless the username you entered is the same as the one you are using now, it will not work.
    {% else %}
    <b>Something went wrong and your membership details could not be retrieved.</b> Please try <a href="{% url 'memberdb:login' %}">logging in</a>.
    {% endif %}
{% else %}
    You can see and modify some of your membership and account details below.
{% endif %}
{% endblock %}

{% block extra_preform %}
<div class="form-row">
    {% include 'membership_summary.html' %}
</div>
<div class="form-row">
    <h4>Membership renewals on record</h4>
    <!-- stuff from the membership record itself -->
    {% if memberships %}
	{% include 'membership_list.html' %}
    {% else %}
    No membership renewal records for your account exist yet. Please <a href="{% url 'memberdb:renew' %}">renew your membership</a> to get started.
    {% endif %}
</div>
<br>
{% endblock %}

{% block form %}
{% if object %} {{ block.super }} {% endif %}
{% endblock %}

{% block postform %}
<div class="form-row">
<p class="help">To update your other membership details, please talk to a door or committee member.</p>
</div>
{% endblock %}

{% block action_url %}{% url 'memberdb:home' %}{% endblock %}

{% block action_text %}Update details{% endblock %}

src/templates/index.html
{% extends "base.html" %}

{% block title %}Gumbies registered in the system{% endblock %}

{% block content %}
{% if member_list %}
    <ul>
    {% for m in member_list %}
        <li><a href="#"><strong>[{{ m.username }}]</strong> {{ m.display_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No members are registered :(</p>
{% endif %}
{% endblock %}

src/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}UCC Member Login{% endblock %}

{% block extrahead %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "login.css" %}">
{{ form.media }}
{% endblock %}

{% block content_title %}<h1>Login to MemberDB</h1>{% endblock %}

{% block content %}

<div class="form-container">

<div class="form-header">
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}Please correct the error below.{% else %}Please correct the errors below.{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}


<p class="tips">
{% if user.is_authenticated %}
    You are already logged in as {{ user.username }}.
    Would you like to login to a different account?
{% else %}
    <b>Please enter your UCC username and password below.</b> <br><br>
    {% if not request.member %}
    If you do not have a UCC account yet, please apply for a membership by going to the <a href="{% url 'memberdb:register' %}">registration page</a>.
    {% else %}
    It appears you have already registered. If you have not yet received your UCC login details, please <a href="https://www.ucc.asn.au/aboutucc/contact.ucc">contact us</a>.
    {% endif %}
{% endif %}
</p>
</div>

<form action="{% url 'memberdb:login' %}" method="post" id="login-form">
  {% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}">
  </div>
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="Log in">
  </div>
</form>
</div>

{% endblock %}

src/templates/logout.html
{% extends "base.html" %}
{% load static %}

{% block title %}UCC Member Logout{% endblock %}

{% block extrahead %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "login.css" %}">
{{ form.media }}
{% endblock %}

{% block content_title %}<h1>Logout</h1>{% endblock %}

{% block content %}

<div class="form-container">

<p>
    <b>You are now logged out of MemberDB.</b>
</p>

<p>
    <a href="{% url 'memberdb:login' %}">Click here</a> to log back in again.
</p>

{% endblock %}

src/templates/membership_list.html
{% load static %}
<table class="membership-details">
	<tr class="{% cycle 'row1' 'row2' as rcl %}">
		<th>Membership type</th>
		<th>Submitted / Updated</th>
		<th>Paid</th>
		<th>Approved</th>
		<th>Actions</th>
	</tr>
	{% for ms in memberships %}
	<tr class="{% cycle rcl %}">
		<td>
			{{ ms.get_pretty_type }}
		</td>
		<td>
			{{ ms.date_submitted |date:"Y-m-d H:i" }}
		</td>
		<td>
			{% if ms.date_paid %}
			<img src="{% static 'admin/img/icon-yes.svg' %}" alt="yes">&nbsp; {{ ms.date_paid |date:"Y-m-d H:i" }}
			{% else %}
			<img src="{% static 'admin/img/icon-no.svg' %}" alt="no">&nbsp; Not paid yet
			{% endif %}
		</td>
		<td>
			{% if ms.date_approved and ms.approved %}
			<img src="{% static 'admin/img/icon-yes.svg' %}" alt="yes">&nbsp; {{ ms.date_approved |date:"Y-m-d H:i" }}
			{% elif ms.date_approved and not ms.approved %}
			<img src="{% static 'admin/img/icon-no.svg' %}" alt="no">&nbsp; Rejected: {{ ms.date_approved |date:"Y-m-d H:i" }}
			{% else %}
			<img src="{% static 'admin/img/icon-unknown.svg' %}" alt="?">&nbsp; Not approved yet
			{% endif %}
		</td>
		<td>
			<!-- membership actions -->
			{% if not ms.date_paid %}
				<a class="button" href="{% url 'squarepay:pay_membership' ms.id %}">Pay now</a>
			{% else %}
				-
			{% endif %}
		</td>
	</tr>
	{% endfor %}
</table>

src/templates/membership_summary.html
{# this template is used by the admin membership renewal page and member homepage #}
{% load static %}
{% block header1 %}
<h4>Current member details</h4>
{% endblock %}
{% block member_details %}
<!-- try to display only the details which aren't editable on member home page -->
<table class="member-details">
    {% block name %}
    <tr class="{% cycle 'row1' 'row2' as rcl %}">
        <th>Real name</th>
        <td><b>{{ member.first_name }} {{ member.last_name }}</b></td>
    </tr>
    <tr class="{% cycle rcl %}">
        <th>Username &amp; display name</th>
        <td><b>{{ member.username }}</b> ({{ member.display_name }})</td>
    </tr>
    {% endblock %}

    {% block email %}
    <tr class="{% cycle rcl %}">
        <th>Contact email</th>
        <td>
        {% if member.email_address %}
            <a href="mailto:{{ member.email_address }}">{{ member.email_address }}</a>
        {% else %}
            <i>not provided</i>
        {% endif %}
        </td>
    </tr>
    {% endblock %}

    {% block phone %}
    <tr class="{% cycle rcl %}">
        <th>Phone number</th>
        <td>{% if member.phone_number %}{{ member.phone_number }}{% else %}<i>not provided</i>{% endif %}</td>
    </tr>
    {% endblock %}

    {% block student %}
    <tr class="{% cycle rcl %}">
        <th>Is student</th>
        <td>{% if member.is_student %}<img src="{% static 'admin/img/icon-yes.svg' %}" alt="yes">{% else %}<img src="{% static 'admin/img/icon-no.svg' %}" alt="no">{% endif %}</td>
    </tr>
    <tr class="{% cycle rcl %}">
        <th>Is UWA Guild</th>
        <td>{% if member.is_guild %}<img src="{% static 'admin/img/icon-yes.svg' %}" alt="yes">{% else %}<img src="{% static 'admin/img/icon-no.svg' %}" alt="no">{% endif %}</td>
    </tr>
    <tr class="{% cycle rcl %}">
        <th>Student number or Other ID</th>
        <td>{% if member.id_number %}{{ member.id_number }}{% else %}<i>not provided</i>{% endif %}</td>
    </tr>
    <tr class="{% cycle rcl %}">
        <th>ID type</th>
        <td>{% if member.id_desc %}{{ member.id_desc }}{% else %}<i>not provided</i>{% endif %}</td>
    </tr>
    {% endblock %}
</table>
{% endblock %}

src/templates/payment_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}UCC Payment Gateway{% endblock %}

{% block extrahead %}

<script type="text/javascript" src="https://web.squarecdn.com/v1/square.js"></script>
{# bring the location IDs into javascript so the next bits know about them #}
<script type="text/javascript">

    var appId = "{{ app_id }}";
    var locationId = "{{ loc_id }}";
    var amount = "{{ payment.amount }}";

    async function initializeCard(payments) {
        const card = await payments.card();
        await card.attach('#card-container');
        return card;
    }

    // Call this function to send a payment token, buyer name, and other details
    // to the project server code so that a payment can be created with 
    // Payments API
    async function createPayment(token, verificationToken) {
        const csrfToken = document.querySelector('input[name=csrfmiddlewaretoken]').value;
        const body = JSON.stringify({
            locationId,
            sourceId: token,
            verificationToken: verificationToken,
        });

        const paymentResponse = await fetch(location.href, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrfToken,
            },
            body,
            credentials: 'same-origin',
        });

        return paymentResponse.json();
    }

    // This function tokenizes a payment method. 
    // The ‘error’ thrown from this async function denotes a failed tokenization,
    // which is due to buyer error (such as an expired card). It is up to the
    // developer to handle the error and provide the buyer the chance to fix
    // their mistakes.
    async function tokenize(paymentMethod) {
        const tokenResult = await paymentMethod.tokenize();
        if (tokenResult.status === 'OK') {
            return tokenResult.token;
        } else {
            let errorMessage = `Tokenization failed-status: ${tokenResult.status}`;
            if (tokenResult.errors) {
                errorMessage += ` and errors: ${JSON.stringify(
                    tokenResult.errors
                )}`;
            }
            throw new Error(errorMessage);
        }
    }

    async function verifyBuyer(payments, token) {
        const verificationDetails = {
            amount: '{{ payment.amount }}',
            /* collected from the buyer */
            billingContact: {},
            currencyCode: 'AUD',
            intent: 'CHARGE',
        };

        const verificationResults = await payments.verifyBuyer(
            token,
            verificationDetails
        );

        return verificationResults.token;
    }

    // Helper method for displaying the Payment Status on the screen.
    // status is either SUCCESS or FAILURE;
    function displayPaymentResults(status) {
        const cardButton = document.getElementById(
            'card-button'
        );
        if (status === 'SUCCESS') {
            cardButton.classList.remove('failure');
            cardButton.classList.add('success');
            cardButton.innerText = 'Payment successful! Redirecting...';
        } else {
            cardButton.classList.remove('success');
            cardButton.classList.add('failure');
            cardButton.innerText = 'Payment failed :( Refreshing...';
        }
    }


    document.addEventListener('DOMContentLoaded', async function () {
        const loader = document.getElementById('spinner');
        const cardButton = document.getElementById(
            'card-button'
        );

        cardButton.disabled = true;
        if (!window.Square) {
            throw new Error('Square.js failed to load properly');
        }
        const payments = window.Square.payments(appId, locationId);
        let card;
        try {
            card = await initializeCard(payments);
            loader.style.display = 'none';
            cardButton.disabled = false;
        } catch (e) {
            console.error('Initializing Card failed', e);
            return;
        }

        async function handlePaymentMethodSubmission(event, paymentMethod, shouldVerify = true) {
            event.preventDefault();
            const token = await tokenize(paymentMethod);

            cardButton.disabled = true;
            cardButton.innerText = "Processing...";

            let verificationToken;
            if (shouldVerify) {
                verificationToken = await verifyBuyer(
                    payments,
                    token
                );
            }

            const paymentResults = await createPayment(token, verificationToken);
            if (paymentResults.success) {
                displayPaymentResults('SUCCESS');
                setTimeout(
                    function () { window.location.href = "{{ payment.completed_url }}"; }, 3000
                );
            } else {
                cardButton.disabled = false;
                displayPaymentResults('FAILURE');
                console.error(paymentResults.errors);
                setTimeout(
                    function () { window.location.href = "{{ payment.completed_url }}"; }, 3000
                );
            }
            console.debug('Payment Success', paymentResults);

        }

        cardButton.addEventListener('click', async function (event) {
            await handlePaymentMethodSubmission(event, card, true);
        });

    });
</script>

<link rel="stylesheet" type="text/css" href="{% static 'squarepay.css' %}">

{% endblock %}


{% block content_title %}<h1>Checkout</h1>{% endblock %}
{% block content %}
<div class="form-container text-center">
    <div class="form-header">
        <span class="tips {% if payment.is_paid %}error{% endif %}">{% block tips %}
            {% if payment.is_paid %}
            <p><b>It appears you have already successfully attempted this payment.</b>
                {% if payment.completed_url %}
                <br><br>Perhaps you were meaning to find <a href="{{ payment.completed_url }}">this page</a>.
                {% endif %}
            </p>
            {% else %}
            <b><i>Please fill in your card details below.</i></b>
            {% endif %}
        </span>
        {% endblock %}

        <noscript>
            <span class="tips error">Please enable javascript to use the payment form.</span>
        </noscript>
    </div>
    <div class="float-container">
        <div class="payment-info">
            <div class="form-row readonly">
                <label for="id_desc">Item:</label>
                <span class="text" id="id_desc">{{ object.description }}</span>
            </div>
            <div class="form-row readonly">
                <label for="id_amount">Amount:</label>
                <span class="text" id="id_amount">{{ amount }}</span>
            </div>
        </div>
        <!-- the element #form-container is used to create the Square payment form (hardcoded) -->
        <div id="form-container" class="payment-info">
            <div class="float-container">
                {% csrf_token %}
                <div id=spinner class="lds-ellipsis" id="payment-form">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
                <form id="payment-form">
                    <div id="card-container"></div>
                    <button id="card-button" type="button">Pay {{ amount }}</button>
                </form>
            </div> <!-- end #float-container -->
        </div> <!-- end #form-container -->
    </div>
</div>
</div>
{% endblock %}

src/templates/register.html
{% extends "base_form.html" %}

{% block title %}UCC Registration{% endblock %}

{% block content_title %}<h1>Register as a new member for {{ year }}</h1>{% endblock %}

{% block tips %}
    Enter your details, and press "Register" when you are done.<br>
    Once your membership has been approved, you will receive an email with further instructions to activate your account.
{% endblock %}

{% block action_url %}{% url 'memberdb:register' %}{% endblock %}
{% block action_text %}Register{% endblock %}

src/templates/renew.html
{% extends "base_form.html" %}
{% block title %}UCC Membership Renewal{% endblock %}
{% block content_title %}
	<h1>Renew your membership for {{ year }}</h1>
{% endblock %}

{% block tips %}
{% if is_new %}
<b>Your account exists already but no membership information has yet been recorded in this system.</b>
<br>Please update/correct the details below as necessary. Some have probably been filled for you.
{% else %}
	{% if last_renewal == year %}
		You have already submitted a membership renewal for {{ year }}. You may update your details below if they have changed, although any changes you make will need to be approved.
	{% else %}
		Please confirm that the details below have not changed since your last registration or membership renewal.
	{% endif %}
{% endif %}
{% endblock %}

{% block extra_preform %}
{% if memberships and last_renewal == year %}
<div class="form-row">
	{% include 'membership_list.html' %}
</div>
{% endif %}
<div class="form-row readonly">
	<label for="id_username">Username:</label>
	<span class="text" id="id_username">{{ request.user.username }}</span>
</div>
{% endblock %}

{% block action_url %}{% url 'memberdb:renew' %}{% endblock %}

{% block action_text %}{% if last_renewal == year %}Save &amp; Update{% else %}Renew{% endif %}{% endblock %}

src/templates/thanks.html
{% extends "base.html" %}

{% block content_title %}
<h1>Thanks!</h1>
{% endblock %}

{% block content %}
<h3>
    Use <a href="{{ login_url }}">this link</a> to access <i>Member Home</i> to see and edit your details, and to pay online for your membership.
</h3>
<p>
Once your registration has been approved, you will receive an email with instructions to activate your account. If you signed up as a student, this information will be sent to the student email address that you provided.
</p>
<p>
{% if request.user.is_authenticated %} <!-- the user is currently logged in, so they may have dispense credit -->
You can either pay online now using your existing dispense credit or using a credit/debit card by going to <a href="{{ login_url }}">Member Home</a>, or you can pay in person later.
{% else %} <!-- the user isn't logged in, but they can still pay -->
You can pay online now with a credit/debit card by going to <a href="{{ login_url }}">Member Home</a>.
{% endif %}
</p>
{% endblock %}